### PR TITLE
add c++11 switch for liblas.a

### PR DESCRIPTION
**Pull request by mrosen**
I needed to add the c++11 switch to get the library to build.

### CODE REVIEW

**Comment by rapidlasso** [comment]
I had not needed it so far. Hope this won't break mine or anyone else's Linux / MacOS builds ...

**Comment by gneissone** [comment]
It broke my build on a machine where I don't have sudo privileges to update the compiler. It's an easy fix, though... just change the flag in LASlib/src/Makefile from -std=c++11 to -std=c++0x.

**Comment by rapidlasso** [comment]
Hey @mrosen, care to weigh in here? Will the c++0x flag work for you too?

**Comment by mrosen** [comment]
Yes, I confirm that either -std flag will work.  I also confirm that
omitting the -std flag causes the failure below.  I'm on Linux using gcc
5.4.

msr@msr-laptop ~/LAStools/LASlib/src $ make
g++  -c -O3 -Wall -Wno-deprecated -Wno-strict-aliasing -Wno-write-strings
-DNDEBUG -DUNORDERED  -I/usr/include/ -I../../LASzip/src -I../inc -I.
../../LASzip/src/lasindex.cpp -o ../../LASzip/src/lasindex.o
In file included from /usr/include/c++/5/unordered_map:35:0,
                 from ../../LASzip/src/lasindex.cpp:51:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file
requires compiler and library support for the ISO C++ 2011 standard. This
support must be enabled with the -std=c++11 or -std=gnu++11 compiler
options.
 #error This file requires compiler and library support \

I have several trees of LAStools here and only the latest one requires this
switch.  I wasn't able to nail it down to a particular change but if
someone wants to chase this, Here's a diff that may help.  The offending
build is version 170625

msr@msr-laptop ~/LAStools/LASlib/src $ diff -r /home/msr/dev/LAStools/
/home/msr/LAStools/ | grep  VERSION
< #define LAS_TOOLS_VERSION 170322
> #define LAS_TOOLS_VERSION 170625
< #define LASZIP_VERSION_MAJOR                2
< #define LASZIP_VERSION_MINOR                5
< #define LASZIP_VERSION_REVISION             2
< #define LASZIP_VERSION_BUILD_DATE      170111
> #define LASZIP_VERSION_MAJOR                3
> #define LASZIP_VERSION_MINOR                0
> #define LASZIP_VERSION_REVISION             1
> #define LASZIP_VERSION_BUILD_DATE      170528

**Comment by gneissone** [comment]
FWIW gcc has supported c++11 since GCC 4.8.1 which was released over 5 years ago. Ideally I would just update gcc but alas...

**Pull request merged**
