### PR TITLE
Prefer wide file strings for MSVC FindFirstFile

### LINKED ISSUE #183: Inconsistent character encoding for opening files
We recently stumbled across the fact that we cannot open files with special characters, such as German umlauts.

As we are using Qt our code was like this:

```cpp
QString relativeFilePath = QString::fromUtf8("las/pointcloud_äöü.las"); // Source file UTF-8 encoded
LASreadOpener lasreadopener;
lasreadopener.set_file_name(relativeFilePath.toLocal8Bit().constData());
auto lasReader = lasreadopener.open();
if (!lasReader)
{
	qWarning() << QObject::tr("Cannot open file %1.").arg(relativeFilePath);
	return;
}
```

This test case failed, so I debugged it. It failed here:
https://github.com/LAStools/LAStools/blob/c3d4641d35b1e26a6982542a8db366daeb9fa4cd/LASlib/src/lasreader_las.cpp#L57-L65

As you can see `file_name` will be converted from UTF-8 to UTF-16 there. So I adjusted my code to use `toUtf8()` instead of `toLocal8Bit()`. This sadly didn't fixed the issue, as now `set_file_name` is failing. Reason is here:
https://github.com/LAStools/LAStools/blob/c3d4641d35b1e26a6982542a8db366daeb9fa4cd/LASlib/src/lasreader.cpp#L2936-L2938

As you can see `FindFirstFile` is used. This method is defined in `fileapi.h` as:
```cpp
#ifdef UNICODE
#define FindFirstFile  FindFirstFileW
#else
#define FindFirstFile  FindFirstFileA
#endif // !UNICODE
```
As `UNICODE` is not defined (and I don't see any export in the CMake script for it), [`FindFirstFileA`](https://learn.microsoft.com/de-de/windows/win32/api/fileapi/nf-fileapi-findfirstfilea) will be used. As it has the suffix `A`, and not `W`, now, it expects a `LPCSTR`, which is a null-terminated string of 8-bit Windows (ANSI) characters. Remember: The `LASreaderLAS::open` called `UTF8toUTF16`, so this expects an UTF-8 string.

I'm not sure why `set_file_name` does more than just storing the given path, but the issue can currently worked around by not using `set_file_name`:
```cpp
LASreadOpener lasreadopener;
auto lasReader = lasreadopener.open(relativeFilePath.toLocal8Bit().constData());
```

### PR DESCRIPTION
**Pull request by thbeu**
This is my attempt to fix #183 for MSVC.

@SunBlack Your test and review is appreciated.

### CODE REVIEW

**Comment by thbeu** [comment]
@SunBlack Any progress so far?

**Comment by SunBlack** [comment]
Sorry for the delay, compiling LASTools is always just pain (the `INSTALL` target of `Debug`-Build requires that you first compile `MinSizeRel`, which requires `RelWithDbgInfo`, ...)

Somehow I'm not able to compile your branch with MSVC 17.9.6 as it stucks compiling the LASlib with `Generating Code...` (but this happens also with your `master` branch).

But I could tried it with the Debug build and there I'm getting an expection
image

Reason seems to be, that `full_file_name` is wrong. `utf16_file_name` seems to be correct. But `full_file_name` contains the just the directory (by the name I would expect that it is the filename and not the path to the file) - and it is not zero terminated. From the immediate window:
```
len
14
full_file_name[13]
47 '/'
full_file_name[14]
-20 'ì'
```

**Comment by thbeu** [comment]
Thanks for the feedback! Do you have a simple command line how I can drive the code?

**Comment by SunBlack** [comment]
Wrote you a small example:

Content of `CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.5...3.29)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

project(lasutf)

find_package(Qt5 REQUIRED Widgets) # Should also work when using Qt6 instead

### manual find_package(LASlib REQUIRED)
find_path(LASlib_INCLUDE_DIR
	NAMES
		lasreader.hpp
	HINTS
		$ENV{LASLIB_DIR}/include
	PATH_SUFFIXES
		laslib
		LASlib
)

find_library(LASlib_LIBRARY
	NAMES
		laslib
		LASlib
	HINTS
		$ENV{LASLIB_DIR}/lib
	PATH_SUFFIXES
		LASlib
		LASlib/Release
)

find_library(LASlib_LIBRARY_DEBUG
	NAMES
		laslibd
		LASlibd
	HINTS
		$ENV{LASLIB_DIR}/lib
	PATH_SUFFIXES
		LASlib
		LASlib/Debug
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
	LASlib DEFAULT_MSG
	LASlib_LIBRARY LASlib_INCLUDE_DIR
)

add_library(LASlib::LASlib STATIC IMPORTED)
set_target_properties(LASlib::LASlib PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${LASlib_INCLUDE_DIR}")

set_property(TARGET LASlib::LASlib APPEND PROPERTY IMPORTED_CONFIGURATIONS "RELEASE")
set_target_properties(LASlib::LASlib PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX")
set_target_properties(LASlib::LASlib PROPERTIES IMPORTED_LOCATION_RELEASE "${LASlib_LIBRARY}")

if(LASlib_LIBRARY_DEBUG)
	set_property(TARGET LASlib::LASlib APPEND PROPERTY IMPORTED_CONFIGURATIONS "DEBUG")
	set_target_properties(LASlib::LASlib PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX")
	set_target_properties(LASlib::LASlib PROPERTIES IMPORTED_LOCATION_DEBUG "${LASlib_LIBRARY_DEBUG}")
endif()
### end find_package(LASlib REQUIRED)

add_executable(${PROJECT_NAME}
	test.cpp
)

target_link_libraries(${PROJECT_NAME}
	PUBLIC
		Qt::Widgets
		LASlib::LASlib
)
```

Content of `test.cpp`

```cpp
#include <QApplication>
#include <QFileDialog>
#include <QMessageBox>

#include <lasreader.hpp>

int main(int argc, char* argv[])
{
	QApplication app(argc, argv);

	const auto fileName = QFileDialog::getOpenFileName();
	if (fileName.isNull())
	{
		QMessageBox::critical(nullptr, {}, "No file selected.");
		return 0;
	}

	LASreadOpener lasreadopener;
	lasreadopener.set_file_name(qUtf8Printable(fileName));
	auto lasReader = lasreadopener.open();
	//auto lasReader = lasreadopener.open(qUtf8Printable(fileName)); // This line instead of both lines above is working
	if (!lasReader)
	{
		QMessageBox::critical(nullptr, {}, "Open failed.");
		return 1;
	}
	QMessageBox::information(nullptr, {}, "Open succeeded.");

	delete lasReader;
	return 0;
}
```

**Comment by thbeu** [comment]
@SunBlack Thanks for test test.cpp. I was able to debug and fix your oberserved bug. Please review again.

I can also confirm that files with umlauts etc. are now correctly found.

**Comment by rapidlasso** [comment]
thanks @thbeu for your  contribution, thanks @SunBlack for testing! we priorized the issue of special chars (#183) now as high, so we will hopefully implement a full utf-8 support for all os soon - we will take your contribution as reference and base.

**Comment by thbeu** [comment]
@rapidlasso Thanks for addressing. Two more comments:

* The final state of this PR was not yet approved/tested by any reviewer (e. g. origial author @SunBlack).
* I believe that #191 is the same issue as #183.

**Comment by rapidlasso** [comment]
done with #197

**Pull request closed without merging**
